
name: PR Preview

on:
  pull_request:
    branches: [ main ]

jobs:
  preview:
    name: Build Preview
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
      
      - name: Install dependencies
        run: npm ci
      
      - name: Build preview
        run: npm run build
      
      - name: Run tests
        run: |
          npm run test:unit
          npx playwright install --with-deps
          npm run test:e2e
        env:
          CI: true
      
      - name: Comment PR
        uses: actions/github-script@v7
        with:
          script: |
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: '✅ Preview build completed successfully! All tests passing.'
            })